# -----------------------------------------------------
# Core
# -----------------------------------------------------

cursor-style = bar
cursor-style-blink = true

scrollback-limit = 2000
mouse-scroll-multiplier = 0.95

focus-follows-mouse = true
mouse-hide-while-typing = true

bell-features = no-audio
confirm-close-surface = false
resize-overlay = never
gtk-toolbar-style = flat

shell-integration = bash
shell-integration-features = no-cursor,ssh-env

# Fix general slowness on hyprland (https://github.com/ghostty-org/ghostty/discussions/3224)
async-backend = epoll