# -----------------------------------------------------
# Keybindings
# -----------------------------------------------------

keybind = performable:ctrl+shift+c=copy_to_clipboard


# Vim-like keybindings
keybind = ctrl+g>g=scroll_to_top
keybind = shift+g>g=scroll_to_bottom


